# This workflow will build a java project with maven

# The name specified here will appear in github workflow
name: Java CI with Maven and Linux

# On specifies when the workflow will be triggered
on:
    push:
       branches:
          - master
    pull_request:
       branches:
          - master

# Workflows are made by one or more jobs
jobs:
    build:
    # Each job needs a runner given by the corresponding virtual environment
        runs-on: ubuntu-latest
        # A job consists in an ordered list pof steps, executed in the same runner
        # They can directly run commands, but this depends on the OS of the runner
        # We can instead use an action
        steps:
              # This action clones the github repository on the runner
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              # This action installs a spoecific version of the Java JDK on the runner
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Build with Maven
              run: mvn clean verify

